@echo off
rem Batch generated by LSD
echo Processing 40 configuration files in up to 2 parallel processes...
if "%~1"=="" (set LSD_EXEC="C:\LSD\Work\Exercicio1_gabriel_porto\lsdNW.exe") else (set LSD_EXEC="%~1")
if "%~2"=="" (set LSD_CONFIG_PATH="C:\LSD\Work\Exercicio1_gabriel_porto") else (set LSD_CONFIG_PATH="%~2")
set LSD_EXEC=%LSD_EXEC:"=%
set LSD_CONFIG_PATH=%LSD_CONFIG_PATH:"=%
echo LSD executable: %LSD_EXEC%
echo Configuration path: %LSD_CONFIG_PATH%
echo Use Sim7.bat LSD_EXEC CONFIG_PATH to change defaults
start "LSD Process 1" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim7" -s 1 -e 20    1> "%LSD_CONFIG_PATH%\Sim7_1.log" 2>&1
start "LSD Process 2" /B "%LSD_EXEC%" -c 1 -f "%LSD_CONFIG_PATH%\Sim7" -s 21 -e 40    1> "%LSD_CONFIG_PATH%\Sim7_2.log" 2>&1
echo 2 log files being generated: Sim7_1.log to Sim7_2.log .
